### ISSUE TITLE
Node execution crash

### ISSUE THREAD

**Issue by rustyblood** [yuvraj108c/ComfyUI-Upscaler-Tensorrt#13]
When using the node and feeding about 4 images coming from a prevous node (image batch), the upscaling process is working fine. It takes about 2-4 seconds to start and it finishes in about another 5 seconds tops.
When feeding more images into another upscaler node, about 20-40 images, it worked properly for about 2 days, then it stoped working. I have deleted the node and insert a new one, but when the node execution begins, I can see the line in the command line window stating that it is loading the Tensorrt engine and it stops, even locking the whole computer. I need to close the terminal window and I can resume activities.
Engine was regenerated 2 times using 2 different onnx models (4x foolhardy and 4x AnimeSharp) with same results. 

![image](https://github.com/yuvraj108c/ComfyUI-Upscaler-Tensorrt/assets/157340830/5cbca3f8-2995-4efd-95e3-6e146f08f245)

**Comment by yuvraj108c** [comment]
Hi, it might be a vram/ram issue, monitor your resources and check if anything is maxing out

**Comment by rustyblood** [comment]
Thank you !!
I made a new workflow and tryed 5, 10, 20, 30 and 40 images (basic generation: checkpoint, prompt, sampler, decode, preview, upscale). It ran perfectly for the first run of each set. After trying a second round of 40 images, it stopped at the beginning of the upscale node. Trying a new rerun, process started to run incredibly slow around half of the process.
Restarting comfyui does not seem to help. Restarting the whole computer allows to re-run the workflow for 1 time, but on the first rerun, it stops again.
Seems that the process is tryig to get as much resources as possible, but after finishing the first run, they might not be freed for the next run.
![image](https://github.com/yuvraj108c/ComfyUI-Upscaler-Tensorrt/assets/157340830/a7877f9b-97ec-4b48-b197-cb15eabe5aa9)

**Comment by yuvraj108c** [comment]
ok, I'll take a look on the issue
thanks for reporting in details

**Comment by rustyblood** [comment]
No problem, thank you for this module. It works really fast, I mean, blazing fast compared with the regular upscaling process (50% o more faster). It helps on reducing time inmensely.

**Comment by rustyblood** [comment]
I tried to get the node again on a new comfyui reinstall from scratch and a new workflow using a 1024 x 640 image resolution, so it should be still within the max 1280 x 1280 resolution. It still works flawlessly on the first run, but starting the second run, it simply halts. Even restarting Comfyui, the node does not start, but restarting the computer allows for a 1 time run, next run halts the computer again.

**Comment by yuvraj108c** [comment]
It is most likely a vram problem. 12gb is not enough based on my tests.

**Comment by rustyblood** [comment]
Got it, thank you for all your support. 
Last question, since the node works at least 1 time with 12Gb with no problems, how can the Vram be "freed" for the next run, allowing for a possible next operation?

**Comment by yuvraj108c** [comment]
Try using a batch manager for upscaling long videos e.g batch manager from videohelpersuite
