### ISSUE TITLE
Latest versions of everything and getting a TensorRT error.

### ISSUE THREAD

**Issue by DarkAlchy** [yuvraj108c/ComfyUI-Upscaler-Tensorrt#14]
[executionContext.cpp::nvinfer1::rt::ExecutionContext::setInputShape::2068] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::nvinfer1::rt::ExecutionContext::setInputShape::2068, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)

I had to get the latest versions to stop another node having issues but now I have issues like this.  Any idea for a fix?

edit:  forgot to add that I did recompile the upscaler engines.

**Comment by yuvraj108c** [comment]
hi, the input image resolutions should be between 256 and 1280 px
if you want higher resolutions edit: https://github.com/yuvraj108c/ComfyUI-Upscaler-Tensorrt/blob/687c695d30253f41c0fc704e3e5700ee01debbcc/export_trt.py#L21

**Comment by DarkAlchy** [comment]
The input image is 1024.
