### ISSUE TITLE
Not issue, just a way to give back to the community - export_trt.py revision.

### ISSUE THREAD

**Issue by DarkAlchy** [yuvraj108c/ComfyUI-Upscaler-Tensorrt#16]
I got tired of typing in the full path for each file to build, and with a lot of them it is insane to do, so I created this revision of the script.  Can still do it via a single file at a time, or just give it the onnx directory and the directory to save the .engine files and away it goes.

I am no github aficionado, so if this is breaking some sort of github etiquette then apologies, but this I am sure will help others. 

![image](https://github.com/yuvraj108c/ComfyUI-Upscaler-Tensorrt/assets/10561690/05b194e3-19f0-4c25-8a7f-8458acc2f799)

Attached is the file (forced zip by Github).
[export_trt_v2.zip](https://github.com/user-attachments/files/15892284/export_trt_v2.zip)

**Comment by yuvraj108c** [comment]
Nice, I'll merge it soon

**Comment by DarkAlchy** [comment]
Coolness. :)
