### ISSUE TITLE
Feature: Resize within upscaler node or target scale

### ISSUE THREAD

**Issue by brandostrong** [yuvraj108c/ComfyUI-Upscaler-Tensorrt#18]
Hi,

Upon large batches of images it's very easily to OOM because of the massive size of upscaled images, it would be nice if the node could resize to the desired size(such as 2x not 4x) within the node, after each image, so it is not so RAM hungry.

**Comment by yuvraj108c** [comment]
It is definitely possible to make, but all currently tested models have a 4x upscale factor, so it won't be as useful
batch manager from videohelpersuite can be used to combat OOM

**Comment by yuvraj108c** [comment]
done
