### ISSUE TITLE
Error when trying export_trt.py

### ISSUE THREAD

**Issue by oliverban** [yuvraj108c/ComfyUI-Upscaler-Tensorrt#19]
Get the following error:
C:\Users\Oliver\Documents\Github\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Upscaler-Tensorrt>python export_trt.py
Traceback (most recent call last):
  File "C:\Users\Oliver\Documents\Github\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Upscaler-Tensorrt\export_trt.py", line 1, in <module>
    import torch
  File "c:\python\Lib\site-packages\torch\__init__.py", line 519, in <module>
    raise ImportError(textwrap.dedent('''
ImportError: Failed to load PyTorch C extensions:
    It appears that PyTorch has loaded the `torch/_C` folder
    of the PyTorch repository rather than the C extensions which
    are expected in the `torch._C` namespace. This can occur when
    using the `install` workflow. e.g.
        $ python setup.py install && python -c "import torch"

    This error can generally be solved using the `develop` workflow
        $ python setup.py develop && python -c "import torch"  # This should succeed
    or by running Python from a different directory.

**Comment by yuvraj108c** [comment]
Try running export_trt.py wihout using comfyui portable (create a new virtual environment somewhere else, clone this repository, install the dependencies, then expor the engines)

not sure how/why comfyui portable causes this error
