### ISSUE TITLE
Could you please add 4xNomos-8k-Hat-L-otf to the converted models?

### ISSUE THREAD

**Issue by EricRollei** [yuvraj108c/ComfyUI-Upscaler-Tensorrt#2]
Here's the link to the model
Thank you!

https://openmodeldb.info/models/4x-Nomos8kHAT-L-otf

**Comment by yuvraj108c** [comment]
After some testing, I found out only models with ESRGAN architecture are working. I need to investigate this issue

**Comment by EricRollei** [comment]
Ok thank you for the efforts, hopefully you can find a way. That nomos model is very good, just very slow so an improvement would be awesome.

**Comment by catboxanon** [comment]
What's the reason this was closed?
