### ISSUE TITLE
Curiosity -- How would I create a version that could handle a 2637 x 768 input?

### ISSUE THREAD

**Issue by LucasMoskun** [yuvraj108c/ComfyUI-Upscaler-Tensorrt#21]
Hello -- thank you for this repo, has been an extreme time (and life) saver. 

At a high level, if I wanted to replicate your work so the .engine can handle a 2637 x 768 input imagine, what would I have to do?

Is it matter of creating the .onnx with alternate parameters? Or would the the base RealESRGAN model itself need to be retrained?

**Comment by yuvraj108c** [comment]
https://github.com/yuvraj108c/ComfyUI-Upscaler-Tensorrt/blob/f316386c9defe5ab974cdf1707f2068b2973fa3a/export_trt.py#L21

just increase the max size in this file & rebuild the tensorrt engine

**Comment by LucasMoskun** [comment]
Thanks for the reply!

I did try that a few times with different resolutions, however I continually receive this error:

```
[E] Error Code: 10: Could not find any implementation for node /model/model.6/Conv.
Building engine: 100%|███████████████████████████████████████████████████████████████████| 6/6 [00:43<00:00,  7.20s/it]
[E] IBuilder::buildSerializedNetwork: Error Code 10: Internal Error (Could not find any implementation for node /model/model.6/Conv.)
[!] Invalid Engine. Please ensure the engine was built correctly
```

**Comment by yuvraj108c** [comment]
Try using multiples of 64 for the resolutions
i'm not sure what's causing the issue, perhaps the resolution is too big

**Comment by LucasMoskun** [comment]
Yes the resolution was too high. I tried small increments and was able to successfully generate .engine's up to 1680 x 1680 on a 4090 before it failed. 
It seemed to fail at the very end of the step "timing graph nodes". 

So a VRAM issue maybe? 

Gonna close this because not really an issue. 

Thanks again for responding!
