### ISSUE TITLE
Can I scale to a customized size?

### ISSUE THREAD

**Issue by AstolfoGPA** [yuvraj108c/ComfyUI-Upscaler-Tensorrt#23]
I´m trying to upscale, keeping the proportions, but its deforming the video.
The input is 512x720 but is upscaling to 720x1280

I trained the engine up to 1024, due to my lowVram (6Vram)

is there any way to keep the proportions?

![Captura de pantalla 2024-09-09 213628](https://github.com/user-attachments/assets/2dbbd6d0-53af-4fa4-8e88-a741057299b8)

**Comment by AstolfoGPA** [comment]
I change the init.py code, to create my customized size, I create a 640x900, its returning a 640x904 video, and proportions looks great.
![Captura de pantalla 2024-09-09 213628](https://github.com/user-attachments/assets/59637cd4-270a-4a00-b551-4af6484012b3)

**Comment by yuvraj108c** [comment]
setting `resize_to` to none should preserve the original aspect ratio
the final size will only be 4 times bigger
