### ISSUE TITLE
Stuck at export_trt.py part of install.

### ISSUE THREAD

**Issue by deadman3000** [yuvraj108c/ComfyUI-Upscaler-Tensorrt#32]
PS C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Upscaler-Tensorrt> python export_trt.py
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Upscaler-Tensorrt\export_trt.py", line 3, in <module>
    from utilities import Engine
ModuleNotFoundError: No module named 'utilities'
PS C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Upscaler-Tensorrt>

I have run requirements.txt and placed one of the onnx models in models/tensorrt/upscaler but no node appears are restarting ComfyUI. I am very bad at command line interfaces so treat me like the idiot I am please.

EDIT: I can load the node but it gives an error

Loading TensorRT engine: C:\ComfyUI_windows_portable\ComfyUI\models\tensorrt\upscaler\4x_foolhardy_Remacri.onnx
[E] IRuntime::deserializeCudaEngine: Error Code 1: Serialization (Serialization assertion plan->header.magicTag == rt::kPLAN_MAGIC_TAG failed.Trying to load an engine created with incompatible serialization version. Check that the engine was not created using safety runtime, same OS was used and version compatibility parameters were set accordingly.)
[!] Could not deserialize engine. See log for details.
!!! Exception during processing !!! Could not deserialize engine. See log for details.
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 313, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 188, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 165, in map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 154, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Upscaler-Tensorrt\__init__.py", line 72, in main
    self.engine.load()
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Upscaler-Tensorrt\utilities.py", line 227, in load
    self.engine = engine_from_bytes(bytes_from_path(self.engine_path))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 3, in engine_from_bytes
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\polygraphy\backend\base\loader.py", line 40, in __call__
    return self.call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\polygraphy\util\util.py", line 710, in wrapped
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\polygraphy\backend\trt\loader.py", line 665, in call_impl
    G_LOGGER.critical("Could not deserialize engine. See log for details.")
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\polygraphy\logger\logger.py", line 605, in critical
    raise ExceptionType(message) from None
polygraphy.exception.exception.PolygraphyException: Could not deserialize engine. See log for details.

I tried running python export_trt.py and it gives an error

PS C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Upscaler-Tensorrt> python export_trt.py
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Upscaler-Tensorrt\export_trt.py", line 3, in <module>
    from utilities import Engine
ModuleNotFoundError: No module named 'utilities'

pip install utilities gives the error

PS C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Upscaler-Tensorrt> pip install utilities
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
ERROR: Could not find a version that satisfies the requirement utilities (from versions: none)
ERROR: No matching distribution found for utilities

**Comment by yuvraj108c** [comment]
Try putting this at the top of `export_trt.py`

```python
import os, sys
file_dir = os.path.dirname(__file__)
sys.path.append(file_dir)
```

**Comment by deadman3000** [comment]
> Try putting this at the top of `export_trt.py`
> 
> ```python
> import os, sys
> file_dir = os.path.dirname(__file__)
> sys.path.append(file_dir)
> ```

This got me past that error but now I don't know what I am doing wrong. I want to use the 4x_foolhardy_Remacri.onnx but the paths and names mess it up. It builds the engine seemingly fine but when I run the workflow it gives the error.

'UpscalerTensorrt
 Could not deserialize engine. See log for details.'

I put the onnx file in "C:\Temp" just to make it easier until I could figure out where I am going wrong (normally it would be in a subfolder of 'models' obviously). I told it to build the engine file in the tensorRT upscaler folder (basically "./4x_foolhardy_Remacri.engine" ).

I'm pulling what little hair I have left out.

**Comment by yuvraj108c** [comment]
use absolute paths instead of relative, it should work
I don't use windows, so it's hard for me to debug these issues
