### ISSUE TITLE
Fail to run upscale

### ISSUE THREAD

**Issue by Piscabo** [yuvraj108c/ComfyUI-Upscaler-Tensorrt#6]
After eventually figuring out, you have to enter the full pathname and filename for the original and output file, I created the *.engine file, but can't use it.

Loading TensorRT engine: C:\AI_Files\ComfyUI\models\tensorrt/upscaler\4x_foolhardy_Remacri.engine
[E] 3: [executionContext.cpp::nvinfer1::rt::ExecutionContext::setInputShape::2309] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::nvinfer1::rt::ExecutionContext::setInputShape::2309, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[E] 3: [executionContext.cpp::nvinfer1::rt::ShapeMachineContext::resolveSlots::2991] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::nvinfer1::rt::ShapeMachineContext::resolveSlots::2991, condition: allInputDimensionsSpecified(routine) )
[E] 3: [executionContext.cpp::nvinfer1::rt::ShapeMachineContext::resolveSlots::2991] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::nvinfer1::rt::ShapeMachineContext::resolveSlots::2991, condition: allInputDimensionsSpecified(routine) )
!!! Exception during processing!!! ERROR: inference failed.
Traceback (most recent call last):
  File "C:\AI_Files\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Files\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Files\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Files\ComfyUI\custom_nodes\ComfyUI-Upscaler-Tensorrt\__init__.py", line 44, in main
    result = engine.infer({"input": img},cudaStream)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Files\ComfyUI\custom_nodes\ComfyUI-Upscaler-Tensorrt\utilities.py", line 266, in infer
    raise ValueError("ERROR: inference failed.")
ValueError: ERROR: inference failed.

**Comment by Piscabo** [comment]
> ok I fixed the issue, update the node and try again!

Unfortunately I still get this:
Loading TensorRT engine: C:\AI_Files\ComfyUI\models\tensorrt\upscaler\4x_foolhardy_Remacri.engine
[E] 3: [executionContext.cpp::nvinfer1::rt::ExecutionContext::setInputShape::2309] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::nvinfer1::rt::ExecutionContext::setInputShape::2309, condition: satisfyProfile Runtime dimension does not satisfy any optimization profile.)
[E] 3: [executionContext.cpp::nvinfer1::rt::ShapeMachineContext::resolveSlots::2991] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::nvinfer1::rt::ShapeMachineContext::resolveSlots::2991, condition: allInputDimensionsSpecified(routine) )
[E] 3: [executionContext.cpp::nvinfer1::rt::ShapeMachineContext::resolveSlots::2991] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::nvinfer1::rt::ShapeMachineContext::resolveSlots::2991, condition: allInputDimensionsSpecified(routine) )
!!! Exception during processing!!! ERROR: inference failed.
Traceback (most recent call last):
  File "C:\AI_Files\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Files\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Files\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Files\ComfyUI\custom_nodes\ComfyUI-Upscaler-Tensorrt\__init__.py", line 44, in main
    result = engine.infer({"input": img},cudaStream)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI_Files\ComfyUI\custom_nodes\ComfyUI-Upscaler-Tensorrt\utilities.py", line 266, in infer
    raise ValueError("ERROR: inference failed.")
ValueError: ERROR: inference failed.

**Comment by yuvraj108c** [comment]
what is the resolutions of the input images?

**Comment by Piscabo** [comment]
> what is the resolutions of the input images? The widths/heights should be between 256 and 1280 px

Yes, you are right it works for these Ratio's only. Thank you. Let's see how I can use it....
![image](https://github.com/yuvraj108c/ComfyUI-Upscaler-Tensorrt/assets/123719842/c64df16c-e8bb-4e28-a2e6-67cc45d6de11)

**Comment by yuvraj108c** [comment]
If you need larger dimensions, edit `export_trt.py` as follows:

 {"input": [(1,3,256,256), (1,3,512,512), (1,3,1280,1280)]}, # any sizes from 256x256 to 1280x1280

increase the 1280, 1280  to whatever dimensions you want

**Comment by yuvraj108c** [comment]
btw, are you using windows 10? I'll update the readme to mention that it works on windows

**Comment by Piscabo** [comment]
> btw, are you using windows 10? I'll update the readme to mention that it works on windows

Working in Windows11. But you have to keep the workflow simple. Trying to use it with a 2x ksampler Workflow has failed, but still testing.
Would be nice if you extend it to some 2x Upscalers too.

**Comment by yuvraj108c** [comment]
ok, what issues are you getting with 2x ksamplers?

yes, i can add some 2x upscalers in the future

**Comment by Piscabo** [comment]
> ok, what issues are you getting with 2x ksamplers?
> 
> yes, i can add some 2x upscalers in the future

No issues... not using 2x, because I need the onnx for that? Or am I wrong...

**Comment by yuvraj108c** [comment]
> No issues... not using 2x, because I need the onnx for that? Or am I wrong...

yep I need to create onnx for the 2x upscalers, then  update the code
